plugins {
    id 'java-library'  // ✅ Necesario para usar 'api'
}

dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'

    // ✅ Ahora funciona 'api'
    api 'io.jsonwebtoken:jjwt-api:0.12.3'
    api 'io.jsonwebtoken:jjwt-impl:0.12.3'
    api 'io.jsonwebtoken:jjwt-jackson:0.12.3'
    api 'org.springframework.security:spring-security-crypto:6.2.1'
}