##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: AuthenticationService
  devtools:
    add-properties: false
adapters:
  r2dbc:
    host: "localhost"
    port: 3300
    database: "crediya_auth"
    schema: "crediya_auth"
    username: "root"
    password: "password"

