server:
  port: 8080
spring:
  application:
    name: "AuthenticationService"
  devtools:
    add-properties: false
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:crediya_auth}"
    user: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    locations: "${FLYWAY_LOCATIONS:classpath:db/migration}"


jwt:
  private-key: "${JWT_PRIVATE_KEY}"
  public-key: "${JWT_PUBLIC_KEY}"
  expiration: 86400000


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: /webjars
  enable-native-support: true
  router-function:
    enabled: true

adapters:
  r2dbc:
    host: "${DB_HOST:localhost}"
    port: ${DB_PORT:3306}
    database: "${DB_NAME:crediya_auth}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    co.com.crediya: DEBUG
    org.springframework.web: DEBUG
