server:
  port: 8080
spring:
  application:
    name: "AuthenticationService"
  devtools:
    add-properties: false
  flyway:
    enabled: true
    url: "jdbc:mysql://localhost:3300/crediya_auth"
    user: "root"
    password: "password"
    locations: "classpath:db/migration"

jwt:
  private-key: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDJ+OOybt+vpkY8I8iA+pP+FDnVQh53gv28+R5hSl+FTi9dIuPMA45nLeTSq1i4WpPlama84R/p+xRy8zm86SNxFjDKJeiTcHQk6U3CLkgD5Q7YOHTLZlY2XDWpTFHJdkO4r9ypcRjHUqm2HH5kiJWn+rMhd/FsWJmBJ2PA9GF5grCWFYzqSlmzlRTCj19XNGr2+TfGkQIn7t+9tncGDdKhInd6nGEIAusN/vyIKvyCj5H1EiIPZtY93f8jSY9qKfjK4GFTuQJC4gfnRSqGgvlLiUSPAf8PcmObr2aLpIhJaNC4lH4S3pWgxGx9Zyi6uKi8kVwIo6YFwEHo4XE9K04pAgMBAAECggEAJOZlh1SNZpR80YECIVpmjm2YkVdWpKQYgp2LCOBjKkI6EgyNTNk7e6tdWoX2nBvkWG5Dne+NepymREgevN5lXMRenpglcUaC2bmMPNViz99aAnPyFrU4PA9FuIwahzGltsjeilCA4+281upGx0xS91EsyAkXYSGgzgFpzrd3VZERVn/aQYS3db3D7rgsTTo8ocGkTkLyGEcSmifeeGelDk8PAqeDIdV/TDW8dRdDC20uNwe5swZoR57R1enmPtq5rMCqH+uty8hBM6awPG2I5aBjzhrWEIulIY0PQ9xFujE6Kw3ZZuArpbX0vOs5CWUT4h7daGjn4qUN0h/LNu/ejwKBgQDasQxObU9vF/mH0tR3giiulUN+wix4QpYmk12UYVUrJZQ2JTq6GhC2BgnZEe5z2U/TAt4xgIhja8CoodtT0oagcqDJgz8DGJVdbGPmNK+HazpZL5GOe2QyeXe3CVekkJs/0LS/VZhRHyPiOI6SJEwaguaoWvdjFJtvQCO6ITnTZwKBgQDsbadbxYkeciVa6r8FWaWtx2aMmeQOKXCmlLHWHojWZH6LW+8huKRC9MHSVkoLHweWO6gzwzIPsy99rjJJ/Jj/DKD76pClEYSxqnb3FzHX/HtRTgAXkB3vV238RFE9FShBLq+eT5n2FcVOGJbSlu9Kq09PYxdBDzTIwZJ3Qwvn7wKBgHrXis8fDcickfkej2RWA54VkCVK0wn2dTtT+fPYPKwQ3tEPVo6lB5AHkk6RiP0gK3ufF8p8paAbLcxLptTN4/uKiBDJnYKSs4wXz4HHRHXv4IWqd7uuShkkK//vyoBRDjPpey4i2X1v3Ys8M7GZm/okX4ZgGqhYMftq7ualtUKvAoGAFueEmBpp7z4lqkolmVIW/9/aanKaKlkPZcPv+otYvFReAgg1AXJOz4HAqSzc3XjzFjXPVLxrRCQazLUsgAhtlf/WNLGDs8ofrcqS3dssY/08wSKqVZ4LmF1C9XZ03FMJZE8uikqx4qo3RBqTufEPW49/DnTOEupzNaOzGcSwCZcCgYAnuWtzuVBNX4HKDE6KH2R/ptg+7LEsU06oE/axBxQIx2VOLfTju6/4TdlKqvK3pm+3U6JTngLaPqUKcDh6BOSRZqcpijrxeq/P1pqVHavCZCkZAMjrwkZU3SWjP2SeF2nAWwJnmdGXZP6yyKu/35m3TF3Ltqw3lpPwU/s8lXnHyQ=="
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyfjjsm7fr6ZGPCPIgPqT/hQ51UIed4L9vPkeYUpfhU4vXSLjzAOOZy3k0qtYuFqT5WpmvOEf6fsUcvM5vOkjcRYwyiXok3B0JOlNwi5IA+UO2Dh0y2ZWNlw1qUxRyXZDuK/cqXEYx1Kpthx+ZIiVp/qzIXfxbFiZgSdjwPRheYKwlhWM6kpZs5UUwo9fVzRq9vk3xpECJ+7fvbZ3Bg3SoSJ3epxhCALrDf78iCr8go+R9RIiD2bWPd3/I0mPain4yuBhU7kCQuIH50UqhoL5S4lEjwH/D3Jjm69mi6SISWjQuJR+Et6VoMRsfWcouriovJFcCKOmBcBB6OFxPStOKQIDAQAB"
  expiration: 86400000
  

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: /webjars
  enable-native-support: true
  router-function:
    enabled: true

adapters:
  r2dbc:
    host: "localhost"
    port: 3300
    database: "crediya_auth"
    schema: "crediya_auth"
    username: "root"
    password: "password"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    co.com.crediya: DEBUG
    org.springframework.web: DEBUG
