##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: AuthenticationService
  devtools:
    add-properties: false
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3300/crediya_auth
    user: root
    password: password
    locations: classpath:db/migration
adapters:
  r2dbc:
    host: "localhost"
    port: 3300
    database: "crediya_auth"
    schema: "crediya_auth"
    username: "root"
    password: "password"

